-- Datos de prueba para RadarApoyoVE
-- Ejecutar después de crear el esquema con supabase-schema.sql
-- NOTA: esto inserta datos de ejemplo. No ejecutar en producción si ya tienes datos reales.

-- 12 puntos de asistencia de ejemplo
INSERT INTO puntos_asistencia (nombre_punto, sector, direccion_exacta, contacto) VALUES
('Refugio Esperanza', 'Catia', 'Av. Principal de Catia, entre calles 12 y 13, antigua escuela Bolívar', '04121234567'),
('Centro de Acopio Chacao', 'Chacao', 'Plaza Bolívar de Chacao, edificio municipal, planta baja', '04241234567'),
('Comedor Comunitario Maiquetía', 'Maiquetía', 'Calle 8, sector Aeropuerto, al lado de la panadería La Virgen', '04161234567'),
('Punto de Acopio Los Corales', 'Los Corales', 'Av. Intercomunal, centro comercial Los Corales, local 5', '04141234567'),
('Albergue La Guaira', 'La Guaira', 'Calle Real de La Guaira, casa 45, frente a la iglesia', '04261234567'),
('Centro Médico Caracas', 'Caracas', 'Av. Urdaneta, edificio San Martín, piso 3', '04121234568'),
('Refugio El Hatillo', 'El Hatillo', 'Calle Sucre, El Hatillo, casa de la cultura', '04141234568'),
('Acopio Baruta', 'Baruta', 'Calle Los Pinos, Baruta, centro comercial Las Delicias', '04241234568'),
('Comedor Sucre', 'Sucre', 'Av. Roosevelt, Petare, sector La Dolorita', '04161234568'),
('Punto de Distribución Catia', 'Catia', 'Mercado de Catia, entrada principal, puesto 12', '04121234569'),
('Centro de Salud Chacao', 'Chacao', 'Av. Libertador, Torre HP, planta baja', '04241234569'),
('Refugio Maiquetía', 'Maiquetía', 'Av. 3 de Mayo, sector Santa Rosa, antiguo colegio', '04161234569');

-- 30 necesidades de ejemplo
INSERT INTO necesidades (punto_id, categoria, descripcion, urgencia, dirigido_a) VALUES
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Medicinas/Salud', 'Necesitamos antisepticos, gasas, vendas y analgesicos para atender heridos leves en el refugio.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Cocina/Alimentos', 'Se requieren alimentos no perecederos: arroz, pasta, lentejas, harina pan y aceite.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Agua/Purificación', 'Falta agua potable. Se necesitan garrafones, tabletas purificadoras y filtros.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Higiene/Pañales', 'Urgente: pañales para bebé y adultos, papel higiénico, jabón y cepillos de dientes.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Transporte/Logística', 'Buscamos camioneta o camión para trasladar insumos entre Catia y La Guaira.', 'Crítica', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Mano de Obra', 'Se necesitan voluntarios para descargar donaciones y organizar el centro de acopio.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Herramientas/Construcción', 'Necesitamos palas, picos, guantes de trabajo y carretillas para remover escombros.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Ropa/Calzado', 'Se solicitan ropa de cama, mantas, zapatos cerrados y ropa seca para adultos y niños.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Electricidad/Plantas', 'El refugio no tiene luz. Necesitamos planta eléctrica, extensiones y bombillos.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Alojamiento/Refugio', 'Familias necesitan colchonetas, hamacas o espacio temporal para dormir.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Combustible/Gas', 'Necesitamos gasolina para transportar ayuda y gas doméstico para cocinar.', 'Crítica', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Comunicación/Internet', 'Se requiere servicio de internet móvil o radios para coordinar equipos de rescate.', 'Moderada', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Medicinas/Salud', 'Falta medicamentos para la presión, insulina y antibióticos básicos.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Cocina/Alimentos', 'Se necesita leche en polvo, cereales y comida para bebés.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Transporte/Logística', 'Motociclista o vehículo para llevar medicinas a zonas de difícil acceso.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Higiene/Pañales', 'Toallas sanitarias, desodorantes, shampoo y pasta dental para familias refugiadas.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Mano de Obra', 'Enfermeros, paramédicos o personal de salud para turnos de atención.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Agua/Purificación', 'Bomba de agua manual y mangueras para distribución en el sector.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Herramientas/Construcción', 'Martillos, clavos, zinc, madera y lazos de plástico para reparar techos.', 'Moderada', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Ropa/Calzado', 'Ropa de trabajo y botas de seguridad para voluntarios en campo.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Alojamiento/Refugio', 'Carpas o toldos para montar refugio temporal en área afectada.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Electricidad/Plantas', 'Baterías portátiles, cargadores solares y cables para mantener comunicación.', 'Moderada', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Comunicación/Internet', 'Teléfonos móviles funcionales o chips con saldo para coordinadores.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Combustible/Gas', 'Tanques de gas propano de 10kg para cocinas comunitarias.', 'Crítica', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Cocina/Alimentos', 'Ollas grandes, utensilios de cocina y gas para preparar comidas colectivas.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Medicinas/Salud', 'Termómetros, tensiómetros, oxímetros y guantes de látex.', 'Moderada', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Transporte/Logística', 'Conductor con camioneta disponible para traslado de personas a refugios.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Higiene/Pañales', 'Bolsas de basura, guantes de limpieza y productos desinfectantes.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Mano de Obra', 'Psicólogos o trabajadores sociales para apoyo emocional a familias afectadas.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Agua/Purificación', 'Sistemas de filtración portátiles y cloro para potabilizar agua.', 'Crítica', 'Ambos');

-- 30 ofertas de voluntarios de ejemplo
INSERT INTO ofertas_voluntarios (nombre_voluntario, contacto, sector_actual, categoria, recurso_ofrecido, activo_hasta, dirigido_a) VALUES
('Carlos Mendoza', '04121234570', 'Catia', 'Transporte/Logística', 'Tengo camioneta pick-up disponible para trasladar insumos médicos y alimentos.', NOW() + INTERVAL '24 hours', 'Ambos'),
('Ana Rojas', '04241234570', 'Chacao', 'Medicinas/Salud', 'Soy enfermera profesional, puedo atender turnos de 4 horas en refugios.', NOW() + INTERVAL '48 hours', 'Personas'),
('Luis Pérez', '04161234570', 'Maiquetía', 'Cocina/Alimentos', 'Puedo preparar 50 comidas diarias en mi restaurante para repartir en refugios.', NOW() + INTERVAL '72 hours', 'Centros de Acopio'),
('María Fernández', '04141234570', 'Los Corales', 'Higiene/Pañales', 'Tengo donación de 100 pañales, jabón, pasta dental y papel higiénico.', NOW() + INTERVAL '36 hours', 'Personas'),
('Pedro Gutiérrez', '04261234570', 'La Guaira', 'Mano de Obra', 'Disponible para ayudar a descargar donaciones y organizar acopios.', NOW() + INTERVAL '24 hours', 'Centros de Acopio'),
('Diana Torres', '04121234571', 'Caracas', 'Agua/Purificación', 'Tengo garrafones y puedo distribuir agua potable en mi sector.', NOW() + INTERVAL '48 hours', 'Personas'),
('Andrés Silva', '04141234571', 'El Hatillo', 'Herramientas/Construcción', 'Presto herramientas: martillos, clavos, palas y guantes para remover escombros.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Gabriela Marín', '04241234571', 'Baruta', 'Alojamiento/Refugio', 'Tengo espacio para recibir a una familia pequeña temporalmente.', NOW() + INTERVAL '24 hours', 'Personas'),
('Ricardo Blanco', '04161234571', 'Sucre', 'Electricidad/Plantas', 'Electricista con experiencia, puedo revisar conexiones y prestar planta eléctrica.', NOW() + INTERVAL '48 hours', 'Ambos'),
('Laura Castillo', '04121234572', 'Catia', 'Ropa/Calzado', 'Donación de ropa usada en buen estado para adultos y niños.', NOW() + INTERVAL '36 hours', 'Personas'),
('Miguel Ángel León', '04161234572', 'Maiquetía', 'Combustible/Gas', 'Puedo proveer gasolina para vehículos de ayuda y traslado.', NOW() + INTERVAL '24 hours', 'Centros de Acopio'),
('Sofía Hernández', '04241234572', 'Chacao', 'Comunicación/Internet', 'Tengo internet móvil ilimitado y puedo compartir datos para coordinación.', NOW() + INTERVAL '48 hours', 'Ambos'),
('Javier Cordero', '04141234572', 'Los Corales', 'Transporte/Logística', 'Moto disponible para llevar medicamentos a zonas de difícil acceso.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Natalia Vargas', '04261234572', 'La Guaira', 'Medicinas/Salud', 'Estudiante de medicina, puedo apoyar en triage básico y primeros auxilios.', NOW() + INTERVAL '24 hours', 'Personas'),
('Fernando Ruiz', '04121234573', 'Caracas', 'Cocina/Alimentos', 'Puedo donar 20 kg de arroz, lentejas, harina y aceite.', NOW() + INTERVAL '48 hours', 'Centros de Acopio'),
('Carmen Salazar', '04141234573', 'El Hatillo', 'Higiene/Pañales', 'Donación de toallas sanitarias, pañales adultos y productos de aseo.', NOW() + INTERVAL '36 hours', 'Personas'),
('Héctor Mora', '04241234573', 'Baruta', 'Mano de Obra', 'Albañil disponible para ayudar en reparaciones de techos y paredes.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Isabella Quintero', '04161234573', 'Sucre', 'Transporte/Logística', 'Tengo carro familiar disponible para traslado de personas.', NOW() + INTERVAL '24 hours', 'Personas'),
('Daniel Soto', '04121234574', 'Catia', 'Agua/Purificación', 'Puedo proveer 100 litros diarios de agua purificada.', NOW() + INTERVAL '48 hours', 'Ambos'),
('Valentina Ríos', '04161234574', 'Maiquetía', 'Herramientas/Construcción', 'Tengo carretilla, palas, picos y guantes para prestar.', NOW() + INTERVAL '72 hours', 'Centros de Acopio'),
('Roberto Peña', '04241234574', 'Chacao', 'Alojamiento/Refugio', 'Casa con espacio para 4 personas, colchonetas y baño disponible.', NOW() + INTERVAL '24 hours', 'Personas'),
('Camila Duarte', '04141234574', 'Los Corales', 'Electricidad/Plantas', 'Puedo prestar baterías portátiles y cargadores solares.', NOW() + INTERVAL '36 hours', 'Ambos'),
('Santiago Méndez', '04261234574', 'La Guaira', 'Ropa/Calzado', 'Donación de zapatos, ropa de trabajo y mantas.', NOW() + INTERVAL '48 hours', 'Personas'),
('Victoria López', '04121234575', 'Caracas', 'Combustible/Gas', 'Tengo un tanque de gas de 18kg para donar a cocina comunitaria.', NOW() + INTERVAL '24 hours', 'Centros de Acopio'),
('Martín Ortega', '04141234575', 'El Hatillo', 'Comunicación/Internet', 'Radios walkie-talkie disponibles para equipos de rescate.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Luciana Navarro', '04241234575', 'Baruta', 'Medicinas/Salud', 'Puedo donar medicamentos de fiebre, dolor y antibióticos.', NOW() + INTERVAL '48 hours', 'Personas'),
('Esteban Palacios', '04161234575', 'Sucre', 'Cocina/Alimentos', 'Tengo ollas industriales y puedo cocinar para 80 personas.', NOW() + INTERVAL '24 hours', 'Centros de Acopio'),
('Mariana Cáceres', '04121234576', 'Catia', 'Higiene/Pañales', 'Donación de cepillos de dientes, shampoo y jabón en barra.', NOW() + INTERVAL '48 hours', 'Personas'),
('Bruno Figueroa', '04161234576', 'Maiquetía', 'Mano de Obra', 'Puedo ayudar en limpieza, desinfección y organización de refugios.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Antonella Reyes', '04241234576', 'Chacao', 'Transporte/Logística', 'Camioneta disponible para recoger donaciones en toda Caracas.', NOW() + INTERVAL '24 hours', 'Ambos');

-- 15 necesidades adicionales
INSERT INTO necesidades (punto_id, categoria, descripcion, urgencia, dirigido_a) VALUES
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Medicinas/Salud', 'Se necesitan medicamentos para el dolor, antiinflamatorios y material de curación para heridos.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Cocina/Alimentos', 'Requerimos alimentos para preparar desayunos y cenas en refugio temporal.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Agua/Purificación', 'Necesitamos agua embotellada y soluciones para purificar agua de pozo.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Alojamiento/Refugio', 'Familias buscan colchonetas, carpas o espacio cubierto para pernoctar.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Herramientas/Construcción', 'Se requieren cascos de seguridad, botas y guantes para trabajos de remoción.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Transporte/Logística', 'Buscamos conductor con camioneta para trasladar ayuda desde La Guaira hasta Caracas.', 'Crítica', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Higiene/Pañales', 'Faltan productos de higiene personal para mujeres y adultos mayores.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Electricidad/Plantas', 'Necesitamos cargadores de batería y linternas para zonas sin electricidad.', 'Moderada', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Mano de Obra', 'Se necesitan cocineros y ayudantes de cocina para comedor comunitario.', 'Moderada', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Ropa/Calzado', 'Donación de ropa seca, zapatos y mantas para personas afectadas.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Comunicación/Internet', 'Necesitamos teléfonos con batería o radios para coordinar rescates.', 'Crítica', 'Ambos'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Combustible/Gas', 'Se requiere gasolina para generadores y vehículos de emergencia.', 'Crítica', 'Centros de Acopio'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Medicinas/Salud', 'Faltan lentes de lectura, bastones y medicamentos para adultos mayores.', 'Moderada', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Cocina/Alimentos', 'Requerimos leche, fórmula infantil y alimentos para bebés.', 'Crítica', 'Personas'),
((SELECT id FROM puntos_asistencia ORDER BY random() LIMIT 1), 'Transporte/Logística', 'Moto o bicicleta para llevar mensajes y medicinas a zonas afectadas.', 'Crítica', 'Ambos');

-- 15 ofertas de voluntarios adicionales
INSERT INTO ofertas_voluntarios (nombre_voluntario, contacto, sector_actual, categoria, recurso_ofrecido, activo_hasta, dirigido_a) VALUES
('Alejandro Castillo', '04121234577', 'Catia La Mar', 'Transporte/Logística', 'Tengo camioneta 4x4 y puedo trasladar personas y carga a refugios.', NOW() + INTERVAL '24 hours', 'Ambos'),
('Daniela Morales', '04241234577', 'Caraballeda', 'Medicinas/Salud', 'Soy técnica en enfermería, puedo apoyar en primeros auxilios y curaciones.', NOW() + INTERVAL '48 hours', 'Personas'),
('Emilio Rojas', '04161234577', 'Guarenas', 'Cocina/Alimentos', 'Puedo preparar comidas para 30 personas y llevarlas a centros de acopio.', NOW() + INTERVAL '72 hours', 'Centros de Acopio'),
('Florencia Delgado', '04141234577', 'Guatire', 'Higiene/Pañales', 'Donación de productos de aseo, pañales y toallas sanitarias.', NOW() + INTERVAL '36 hours', 'Personas'),
('Gustavo Herrera', '04261234577', 'Aragua', 'Mano de Obra', 'Disponible para ayudar en desmantelamiento de estructuras inseguras.', NOW() + INTERVAL '24 hours', 'Ambos'),
('Inés Vargas', '04121234578', 'Carabobo', 'Agua/Purificación', 'Tengo garrafones de agua purificada y puedo distribuir en mi zona.', NOW() + INTERVAL '48 hours', 'Personas'),
('Joaquín Paredes', '04141234578', 'Falcón', 'Herramientas/Construcción', 'Presto herramientas de construcción y ayudo en reparaciones menores.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Karen Blanco', '04241234578', 'Yaracuy', 'Alojamiento/Refugio', 'Tengo un cuarto disponible para una persona o una pareja temporalmente.', NOW() + INTERVAL '24 hours', 'Personas'),
('Leonardo Soto', '04161234578', 'El Paraíso', 'Electricidad/Plantas', 'Soy electricista y puedo revisar instalaciones eléctricas dañadas.', NOW() + INTERVAL '48 hours', 'Ambos'),
('Mónica Carrillo', '04121234579', 'San Bernardino', 'Ropa/Calzado', 'Donación de ropa de cama, mantas y abrigos para niños y adultos.', NOW() + INTERVAL '36 hours', 'Personas'),
('Nicolás León', '04161234579', 'Los Palos Grandes', 'Combustible/Gas', 'Puedo proveer gasolina para vehículos de ayuda humanitaria.', NOW() + INTERVAL '24 hours', 'Centros de Acopio'),
('Olivia Fuentes', '04241234579', 'Caracas', 'Comunicación/Internet', 'Tengo internet satelital portátil y puedo compartir con coordinadores.', NOW() + INTERVAL '48 hours', 'Ambos'),
('Pablo Mejía', '04141234579', 'La Guaira', 'Transporte/Logística', 'Moto disponible para entregar medicamentos y mensajes urgentes.', NOW() + INTERVAL '72 hours', 'Ambos'),
('Romina Salazar', '04261234579', 'Maiquetía', 'Medicinas/Salud', 'Puedo donar medicamentos para el resfrío, dolor y estómago.', NOW() + INTERVAL '24 hours', 'Personas'),
('Samuel Díaz', '04121234580', 'Catia', 'Cocina/Alimentos', 'Puedo donar 15 kg de arroz, pasta y aceite para cocina comunitaria.', NOW() + INTERVAL '48 hours', 'Centros de Acopio');
